[package]
name = "p0nd_os"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "p0nd_os"
test = false
bench = false

[dependencies]
bootloader = "0.9"
volatile = "0.2.6"
spin = "0.5.2"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

# Since the panic strategy is specified in the os JSON file, we don't need to specify it here.
# the profile used for `cargo build`
# [profile.dev]
# panic = "abort" # disable stack unwinding on panic

# the profile used for `cargo build --release`
# [profile.release]
# panic = "abort" # disable stack unwinding on panic
